### ISSUE TITLE
Associated dataset

### ISSUE THREAD

**Issue by LNshuti** [saeed349/Advances-in-Financial-Machine-Learning#1]
Hi! Thanks for creating such a useful repo. Could you share the associated data for reproducibility? I know the datasets are fairly large and would be happy to use git lfs or host the data on a public AWS S3 repo if you can make the data available. Cheers!

**Comment by saeed349** [comment]
Hi, unfortunately I can't share/distribute the data due to agreement with the data provider. 
You can easily get this data from https://databento.com/ (they have a new user free 125$ credit) or from https://www.kibot.com.

**Comment by LNshuti** [comment]
Very understandable! Thanks for a fast response and for sharing your very useful code. Cheers!
